/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsGithubTokenRouteImport } from './routes/settings.github-token'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo.index'
import { Route as OwnerRepoSplatRouteImport } from './routes/$owner.$repo.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGithubTokenRoute = SettingsGithubTokenRouteImport.update({
  id: '/settings/github-token',
  path: '/settings/github-token',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoSplatRoute = OwnerRepoSplatRouteImport.update({
  id: '/$owner/$repo/$',
  path: '/$owner/$repo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/github-token': typeof SettingsGithubTokenRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/github-token': typeof SettingsGithubTokenRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/github-token': typeof SettingsGithubTokenRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/settings/github-token' | '/$owner/$repo/$' | '/$owner/$repo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/github-token' | '/$owner/$repo/$' | '/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/settings/github-token'
    | '/$owner/$repo/$'
    | '/$owner/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsGithubTokenRoute: typeof SettingsGithubTokenRoute
  OwnerRepoSplatRoute: typeof OwnerRepoSplatRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/github-token': {
      id: '/settings/github-token'
      path: '/settings/github-token'
      fullPath: '/settings/github-token'
      preLoaderRoute: typeof SettingsGithubTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/$': {
      id: '/$owner/$repo/$'
      path: '/$owner/$repo/$'
      fullPath: '/$owner/$repo/$'
      preLoaderRoute: typeof OwnerRepoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsGithubTokenRoute: SettingsGithubTokenRoute,
  OwnerRepoSplatRoute: OwnerRepoSplatRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
